# Changes this file are not auto-reloaded.
# Run `bundle exec jekyll serve` again to reload this data.



# Global Data
title: Nick Maclean
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
  
baseurl: /-folio-theme # the subpath of your site, e.g. /blog/
url: https://nicolasmaclean.com/-folio-theme/



# Build settings
markdown: kramdown
highlighter: rouge

include: ["_pages", "_redirects"]
exclude: ["README.md", "Gemfile", "Gemfile.lock"]

plugins:
  - jekyll-redirect-from



defaults:
  - scope:
      path: _posts
    values:
      layout: post
      permalink: /posts/:year/:title/



# Compress.html (html minifier)
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]